# Molecule managed

FROM phusion/baseimage:bionic-1.0.0

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# ...put your own build instructions here...


{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

ENV APT_PROXY "http://172.17.0.1:3142"
ENV DEBIAN_FRONTEND noninteractive


RUN if [ $APT_PROXY ]; then sed -i 's/https:\/\//http:\/\/HTTPS\/\/\//' /etc/apt/sources.list; fi \
    && if [ $APT_PROXY ]; then echo  "Acquire::http::Proxy \"$APT_PROXY\";" | tee /etc/apt/apt.conf.d/00aptproxy ; fi \
    && apt-get update \
    && apt-get install -y python3 python3-pip sudo bash ca-certificates iproute2 python3-apt aptitude \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /etc/apt/apt.conf.d/00aptproxy \
    ;

CMD $(spire_home)/bin/spire-server run -config $(spire_home)/conf/server/server2.conf -logLevel 'debug'
